import Head from "next/head";
import Image from "next/image";
import Search from "../components/Search";

export default function Home() {
  return (
    <>
    < Head>
          <title>Library Mage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <main class="main-home">
        <video className="hero-video" autoplay="autoplay" loop="loop" muted="muted" playsinline="playsinline" webkit-playsinline="webkit-playsinline" x5-playsinline="x5-playsinline" poster="//images.ctfassets.net/s5n2t79q9icq/3tllC9jZIwZzeydsh7nyMF/171a6641ec395d7479a8ed32fb888361/2017_znr_gen_a01_1920x1080pre.jpg?w=1920&amp;q=70&amp;fm=webp" class="css-ki-qj"><source src="https://videos.ctfassets.net/s5n2t79q9icq/5OjN7Y4jYPFzuoRxpXFpLJ/735410acffa42a0440bdb2d1cde2ca4b/znr_gen_a01_1920x1120_na.mp4" type="video/mp4" /></video>
        

        <div className="search-container">
          <Search />
        </div>
      </main>

      <footer className="footer"></footer>
    </>
  );
}
